enum ContextMenuOptions {
  setBackground = 'set background',
  openRootFolder = 'open root folder',
  renamePCIcon = 'rename PC icon',
  addFile = 'add file',
  addFolder = 'add folder',
  openDirectory = 'open directory',
  cutDirectory = 'cut directory',
  copyDirectory = 'copy directory',
  pasteDirectory = 'paste directory',
  deleteDirectory = 'delete directory',
  openFile = 'open file',
  cutFile = 'cut file',
  copyFile = 'copy file',
  pasteFile = 'paste file',
  deleteFile = 'delete file',
  rename = 'rename',
  minimize = 'minimize',
  maximize = 'maximize',
  close = 'close',
  enterFullScreen = 'enter full screen',
  separator = '',
}

export default ContextMenuOptions;
